import { DocumentTemplate } from "../types";

export const DEFAULT_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
    id: "tpl_termo_aceite_extensao",
    title: "Termo de Aceite do Parceiro de Extensão",
    code: "EXT-ACEITE-01",
    category: "EXTENSAO",
    description: "Termo formal de anuência e compromisso mútuo entre organização parceira e o IFPR Campus Ivaiporã na Disciplina de Extensão.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\nINSTITUTO FEDERAL DO PARANÁ — CAMPUS IVAIPORÃ\nDISCIPLINA DE EXTENSÃO · BACHARELADO EM SISTEMAS DE INFORMAÇÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "Instituto Federal do Paraná — Campus Ivaiporã · Rodovia PR-466, Gleba Pindaúba, Ivaiporã/PR",
    sections: [
      {
        id: "sec_intro",
        title: "Introdução e Finalidade",
        type: "paragraph",
        content:
          "O presente Termo de Aceite formaliza a parceria institucional e pedagógica entre a organização/entidade parceira e o Instituto Federal do Paraná (IFPR) - Campus Ivaiporã, no âmbito curricular das Atividades de Extensão do curso de Bacharelado em Sistemas de Informação. A cooperação tem por finalidade o diagnóstico de demandas comunitárias e o desenvolvimento de soluções computacionais aplicadas em benefício direto da comunidade atendida.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_parceiro",
        title: "1. Dados do Parceiro / Entidade Beneficiada",
        type: "numbered_section",
        content:
          "• Nome da Organização / Grupo: {{nome_organizacao}}\n• Responsável / Representante Legal: {{responsavel}}\n• Cargo / Função: {{cargo_responsavel}}\n• Contato (Telefone / E-mail): {{contato}}\n• Endereço / Local de Atuação: {{endereco_parceiro}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_equipe",
        title: "2. Dados da Equipe de Estudantes e Coordenação",
        type: "numbered_section",
        content:
          "• Nome da Equipe / Projeto: {{nome_equipe}}\n• Integrantes (Estudantes): {{integrantes}}\n• Professor(a) Responsável / Orientador: {{professor_responsavel}}\n• Período Letivo / Semestre: {{periodo_letivo}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_necessidade",
        title: "3. Necessidade / Oportunidade Identificada",
        type: "numbered_section",
        content:
          "{{necessidade_identificada}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao",
        title: "4. Declaração de Aceite e Compromisso Mútuo",
        type: "declarations_list",
        content:
          "I. A organização parceira declara ter pleno conhecimento da natureza acadêmico-extensionista das atividades e autoriza a equipe de estudantes a realizar o levantamento de processos e requisitos técnicos necessários ao projeto.\n\nII. A equipe de estudantes e o IFPR comprometem-se a zelar pelo sigilo e confidencialidade de quaisquer dados sensíveis fornecidos pela parceira durante a execução das etapas extensionistas.\n\nIII. O parceiro compromete-se a disponibilizar canal de diálogo com a equipe para alinhamento de entregas e validação dos protótipos construídos.\n\nIV. A transferência do código-fonte e documentação resultante dar-se-á de forma livre e aberta, sem ônus financeiro para nenhuma das partes, visando o fortalecimento socioeconômico da comunidade local.",
        fontSize: 9.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_org",
        name: "nome_organizacao",
        label: "Nome da Organização / Entidade",
        type: "text",
        defaultValue: "Associação Comunitária de Produtores e Moradores de Ivaiporã",
        placeholder: "Ex: Associação Comercial, Cooperativa, Escola Municipal...",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_resp",
        name: "responsavel",
        label: "Responsável / Representante Legal",
        type: "text",
        defaultValue: "Carlos Eduardo Silva",
        placeholder: "Nome completo do representante",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_cargo_resp",
        name: "cargo_responsavel",
        label: "Cargo / Função do Representante",
        type: "text",
        defaultValue: "Presidente da Diretoria",
        placeholder: "Ex: Diretor Geral, Coordenador, Presidente...",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_contato",
        name: "contato",
        label: "Contato (Telefone e E-mail)",
        type: "text",
        defaultValue: "(43) 99876-5432 / contato@associacao.org.br",
        placeholder: "Telefone / WhatsApp / E-mail",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_end_parceiro",
        name: "endereco_parceiro",
        label: "Endereço / Local de Atuação",
        type: "text",
        defaultValue: "Av. Brasil, nº 1250 - Centro, Ivaiporã - PR",
        placeholder: "Rua, número, bairro, cidade",
        required: false,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_equipe",
        name: "nome_equipe",
        label: "Nome da Equipe / Projeto",
        type: "text",
        defaultValue: "Equipe InovaIF - Sistema de Gestão e Achados Comunitários",
        placeholder: "Ex: Equipe Alpha, ConectaVale...",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_integrantes",
        name: "integrantes",
        label: "Integrantes (Estudantes)",
        type: "textarea",
        defaultValue: "Paulo Cauan de Souza (Matrícula: 20261001), Lucas Gabriel Ribeiro (Matrícula: 20261002), Matheus Henrique Santos (Matrícula: 20261003)",
        placeholder: "Nomes completos e matrículas dos estudantes",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_prof",
        name: "professor_responsavel",
        label: "Professor(a) Responsável / Orientador",
        type: "text",
        defaultValue: "Prof. Me. Rodrigo dos Santos",
        placeholder: "Nome do docente orientador",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_periodo",
        name: "periodo_letivo",
        label: "Período Letivo / Semestre",
        type: "text",
        defaultValue: "2º Semestre / 2026",
        placeholder: "Ex: 2026/2",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_necessidade",
        name: "necessidade_identificada",
        label: "Necessidade / Oportunidade Identificada",
        type: "textarea",
        defaultValue:
          "Identificou-se a ausência de um mecanismo digital centralizado para registro, catalogação e recuperação transparente de demandas e itens da entidade, ocasionando retrabalho manual em planilhas físicas e perda de informações históricas. A solução computacional web/mobile desenvolvida possibilitará automação de processos, geração de relatórios de auditoria e rastreabilidade ágil para atendimento aos cidadãos.",
        placeholder: "Descreva detalhadamente a oportunidade identificada e o impacto esperado",
        required: true,
        section: "3. Necessidade Identificada",
      },
      {
        id: "fld_data",
        name: "data",
        label: "Data do Documento",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Ex: 17 de agosto de 2026",
        required: true,
        section: "Local e Assinaturas",
      },
      {
        id: "fld_rep_equipe",
        name: "representante_equipe",
        label: "Nome do Representante da Equipe (Estudante Líder)",
        type: "text",
        defaultValue: "Paulo Cauan de Souza",
        placeholder: "Nome do estudante representante",
        required: true,
        section: "Local e Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_parceiro",
        title: "Representante da Organização Parceira",
        nameTag: "{{responsavel}}",
        roleTag: "{{cargo_responsavel}}",
        cpfOrDocTag: "{{nome_organizacao}}",
      },
      {
        id: "sig_equipe",
        title: "Representante da Equipe de Estudantes",
        nameTag: "{{representante_equipe}}",
        roleTag: "Líder da Equipe - BSI IFPR",
        cpfOrDocTag: "Campus Ivaiporã",
      },
      {
        id: "sig_orientador",
        title: "Visto do Professor(a) Orientador(a)",
        nameTag: "{{professor_responsavel}}",
        roleTag: "Docente / Coordenador de Extensão",
        cpfOrDocTag: "IFPR Campus Ivaiporã",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },
  {
    id: "tpl_termo_devolucao_objeto",
    title: "Termo de Entrega e Devolução de Objeto de Valor",
    code: "SEC-DEV-02",
    category: "ACHADOS_PERDIDOS",
    description: "Comprovante formal com fé pública de devolução de pertences custodiados pelo balcão de Achados e Perdidos do IFPR Campus Ivaiporã.",
    status: "ATIVO",
    version: 1,
    headerText: "INSTITUTO FEDERAL DO PARANÁ — CAMPUS IVAIPORÃ\nSETOR DE ATENDIMENTO E CUSTÓDIA DE PERTENCES · SEBAC",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "IFPR Campus Ivaiporã · Sistema Oficial de Custódia e Gestão de Pertences",
    sections: [
      {
        id: "sec_intro_dev",
        title: "Declaração de Retirada e Entrega",
        type: "paragraph",
        content:
          "O presente Termo atesta que o objeto abaixo descrito, custodiado no setor de Achados e Perdidos do IFPR Campus Ivaiporã, foi devidamente devolvido ao seu legítimo proprietário/reclamante após conferência documental e comprovação de titularidade.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_item_dev",
        title: "1. Identificação do Objeto Custodiado",
        type: "numbered_section",
        content:
          "• Descrição do Item: {{titulo_item}}\n• Categoria / Cor / Marca: {{categoria_item}} / {{cor_item}} / {{marca_item}}\n• Código de Rastreabilidade / Protocolo: {{codigo_protocolo}}\n• Local e Data do Recolhimento: {{local_recolhimento}} em {{data_recolhimento}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_retirante_dev",
        title: "2. Dados do Reclamante / Proprietário",
        type: "numbered_section",
        content:
          "• Nome Completo: {{nome_reclamante}}\n• Vínculo Institucional / Curso: {{vinculo_reclamante}}\n• Matrícula / CPF / RG: {{documento_reclamante}}\n• Contato Telefônico / E-mail: {{contato_reclamante}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao_dev",
        title: "3. Declaração do Reclamante",
        type: "declarations_list",
        content:
          "Declaro, sob as penas da lei e do regulamento disciplinar do IFPR, que recebi o bem acima caracterizado em perfeito estado de conservação, dando plena e irrevogável quitação de custódia à instituição.",
        fontSize: 10,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_dev",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_tit_item",
        name: "titulo_item",
        label: "Título / Descrição do Item",
        type: "text",
        defaultValue: "Notebook Dell Inspiron 15 Cinza + Carregador",
        placeholder: "Ex: Smartphone Samsung Galaxy, Chaves...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_cat_item",
        name: "categoria_item",
        label: "Categoria do Item",
        type: "text",
        defaultValue: "Eletrônicos & Informática",
        placeholder: "Ex: Documentos, Eletrônicos...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_cor_item",
        name: "cor_item",
        label: "Cor Predominante",
        type: "text",
        defaultValue: "Cinza Metálico",
        placeholder: "Ex: Preto, Azul...",
        required: false,
        section: "1. Dados do Item",
      },
      {
        id: "fld_marca_item",
        name: "marca_item",
        label: "Marca / Modelo",
        type: "text",
        defaultValue: "Dell Inspiron 15 3000",
        placeholder: "Ex: Apple, Samsung, Nike...",
        required: false,
        section: "1. Dados do Item",
      },
      {
        id: "fld_prot_item",
        name: "codigo_protocolo",
        label: "Código / Protocolo do Sistema",
        type: "text",
        defaultValue: "IFPR-2026-B8492X",
        placeholder: "Protocolo do registro",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_loc_item",
        name: "local_recolhimento",
        label: "Local do Recolhimento",
        type: "text",
        defaultValue: "Laboratório de Informática 03 (Bloco B)",
        placeholder: "Ex: Biblioteca, Pátio...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_dt_item",
        name: "data_recolhimento",
        label: "Data do Recolhimento",
        type: "text",
        defaultValue: "10 de agosto de 2026",
        placeholder: "Data em que foi encontrado",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_rec_nome",
        name: "nome_reclamante",
        label: "Nome do Reclamante / Proprietário",
        type: "text",
        defaultValue: "Mariana Alcantara Lopes",
        placeholder: "Nome completo de quem está retirando",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_vinc",
        name: "vinculo_reclamante",
        label: "Vínculo Institucional",
        type: "text",
        defaultValue: "Estudante - Técnico em Informática Integrado",
        placeholder: "Ex: Estudante BSI, Servidor Docente, Visitante...",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_doc",
        name: "documento_reclamante",
        label: "Matrícula / Documento (CPF ou RG)",
        type: "text",
        defaultValue: "Matrícula: 2024104928 / RG: 12.345.678-9 PR",
        placeholder: "Matrícula ou CPF/RG",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_cont",
        name: "contato_reclamante",
        label: "Telefone e E-mail de Contato",
        type: "text",
        defaultValue: "(43) 98877-6655 / mariana.lopes@estudantes.ifpr.edu.br",
        placeholder: "Telefone / E-mail institucional",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_serv_nome",
        name: "servidor_atendente",
        label: "Nome do Servidor Responsável pela Entrega",
        type: "text",
        defaultValue: "Paulo Cauan - Administrador TI",
        placeholder: "Nome do servidor responsável",
        required: true,
        section: "3. Atendimento",
      },
      {
        id: "fld_data_dev",
        name: "data",
        label: "Data da Devolução",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Atendimento",
      },
    ],
    signatures: [
      {
        id: "sig_rec",
        title: "Reclamante / Proprietário do Objeto",
        nameTag: "{{nome_reclamante}}",
        roleTag: "{{vinculo_reclamante}}",
        cpfOrDocTag: "{{documento_reclamante}}",
      },
      {
        id: "sig_serv",
        title: "Servidor / Atendente Responsável (IFPR)",
        nameTag: "{{servidor_atendente}}",
        roleTag: "Setor de Custódia e Patrimônio",
        cpfOrDocTag: "IFPR Campus Ivaiporã",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },
  {
    id: "tpl_termo_doacao_objeto",
    title: "Termo de Destinação e Doação Comunitária (Objetos Não Reclamados)",
    code: "DIR-DOA-03",
    category: "INSTITUCIONAL",
    description: "Termo legal de doação de bens não reclamados após o prazo regulamentar de 90 dias para instituições filantrópicas de Ivaiporã.",
    status: "ATIVO",
    version: 1,
    headerText: "INSTITUTO FEDERAL DO PARANÁ — CAMPUS IVAIPORÃ\nDIREÇÃO GERAL · COMISSÃO PERMANENTE DE DESTINAÇÃO DE BENS",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "IFPR Campus Ivaiporã · Destinação Social de Bens Não Reclamados",
    sections: [
      {
        id: "sec_intro_doa",
        title: "Fundamentação e Finalidade",
        type: "paragraph",
        content:
          "O presente Termo de Doação formaliza a entrega e transferência de titularidade de bens e vestuários não reclamados, após escoado o prazo regulamentar de 90 (noventa) dias de guarda no setor de Achados e Perdidos do IFPR Campus Ivaiporã, nos termos do Regulamento Interno de Custódia e da legislação vigente de destinação de bens desamparados.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_entidade_doa",
        title: "1. Entidade Filantrópica / Donatária Beneficiada",
        type: "numbered_section",
        content:
          "• Razão Social / Nome da Entidade: {{entidade_donataria}}\n• CNPJ: {{cnpj_donataria}}\n• Representante Legal: {{representante_donataria}}\n• Cargo / Função: {{cargo_donataria}}\n• Contato Telefônico: {{telefone_donataria}}\n• Endereço: {{endereco_donataria}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_itens_doa",
        title: "2. Relação de Itens Doados",
        type: "numbered_section",
        content:
          "• Quantidade Total de Itens: {{quantidade_itens}} volumes\n• Descrição Sintética dos Lotes: {{descricao_lotes}}\n• Prazo de Guarda Expirado em: {{data_expiracao_guarda}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao_doa",
        title: "3. Declaração de Recebimento",
        type: "declarations_list",
        content:
          "A entidade donatária declara ter recebido os bens relacionados para emprego exclusivo em suas finalidades estatutárias de assistência social, sem fins lucrativos, agradecendo a iniciativa comunitária do IFPR Campus Ivaiporã.",
        fontSize: 10,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_doa",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_ent_doa",
        name: "entidade_donataria",
        label: "Nome da Entidade Donatária",
        type: "text",
        defaultValue: "Lar dos Idosos São Vicente de Paulo de Ivaiporã",
        placeholder: "Nome da instituição beneficente",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_cnpj_doa",
        name: "cnpj_donataria",
        label: "CNPJ da Entidade",
        type: "text",
        defaultValue: "75.123.456/0001-89",
        placeholder: "00.000.000/0000-00",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_rep_doa",
        name: "representante_donataria",
        label: "Representante Legal da Donatária",
        type: "text",
        defaultValue: "Ana Maria de Fátima Rezende",
        placeholder: "Nome do diretor/presidente",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_cargo_doa",
        name: "cargo_donataria",
        label: "Cargo / Função",
        type: "text",
        defaultValue: "Diretora Social",
        placeholder: "Ex: Presidente, Diretora...",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_tel_doa",
        name: "telefone_donataria",
        label: "Telefone de Contato",
        type: "text",
        defaultValue: "(43) 3472-1234",
        placeholder: "(00) 0000-0000",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_end_doa",
        name: "endereco_donataria",
        label: "Endereço da Entidade",
        type: "text",
        defaultValue: "Rua Ceará, nº 450 - Ivaiporã - PR",
        placeholder: "Endereço completo",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_qtd_doa",
        name: "quantidade_itens",
        label: "Quantidade Total de Itens",
        type: "text",
        defaultValue: "28 itens de vestuário e agasalhos",
        placeholder: "Ex: 15 peças de roupas, 5 garrafas...",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_desc_lotes",
        name: "descricao_lotes",
        label: "Descrição Sintética dos Lotes",
        type: "textarea",
        defaultValue: "Lote 01: 18 casacos e moletons infantis/adultos; Lote 02: 10 calças e agasalhos esportivos em perfeito estado de higienização.",
        placeholder: "Detalhamento dos lotes doados",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_dt_exp",
        name: "data_expiracao_guarda",
        label: "Data de Expiração do Prazo de Guarda",
        type: "text",
        defaultValue: "30 de junho de 2026",
        placeholder: "Data em que completou 90 dias",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_dir_ifpr",
        name: "diretor_ifpr",
        label: "Diretor Geral / Presidente da Comissão IFPR",
        type: "text",
        defaultValue: "Direção Geral do IFPR Campus Ivaiporã",
        placeholder: "Nome do Diretor Geral do Campus",
        required: true,
        section: "3. Assinaturas",
      },
      {
        id: "fld_data_doa",
        name: "data",
        label: "Data da Doação",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_don",
        title: "Representante da Entidade Donatária",
        nameTag: "{{representante_donataria}}",
        roleTag: "{{cargo_donataria}}",
        cpfOrDocTag: "{{entidade_donataria}}",
      },
      {
        id: "sig_dir",
        title: "Direção Geral / Comissão Permanente",
        nameTag: "{{diretor_ifpr}}",
        roleTag: "Instituto Federal do Paraná",
        cpfOrDocTag: "Campus Ivaiporã",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },
];
