import { DocumentTemplate } from "../types";

export const DEFAULT_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  // 1. Termo de Aceite do Parceiro de Extensão
  {
    id: "tpl_termo_aceite_extensao",
    title: "Termo de Aceite do Parceiro de Extensão",
    code: "EXT-ACEITE-01",
    category: "EXTENSAO",
    description: "Termo formal de anuência e compromisso mútuo entre organização parceira e o IFPR Campus Ivaiporã na Disciplina de Extensão do curso de BSI.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nDISCIPLINA DE EXTENSÃO · BACHARELADO EM SISTEMAS DE INFORMAÇÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_intro",
        title: "Introdução e Finalidade",
        type: "paragraph",
        content:
          "O presente Termo de Aceite formaliza a parceria institucional e pedagógica entre a organização/entidade parceira e o {{instituicao}} - {{campus}}, no âmbito curricular das Atividades de Extensão do curso de Bacharelado em Sistemas de Informação. A cooperação tem por finalidade o diagnóstico de demandas comunitárias e o desenvolvimento de soluções computacionais aplicadas em benefício direto da comunidade atendida.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_parceiro",
        title: "1. Dados do Parceiro / Entidade Beneficiada",
        type: "numbered_section",
        content:
          "• Nome da Organização / Grupo: {{nome_organizacao}}\n• Responsável / Representante Legal: {{responsavel}}\n• Cargo / Função: {{cargo_responsavel}}\n• Contato (Telefone / E-mail): {{contato}}\n• Endereço / Local de Atuação: {{endereco_parceiro}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_equipe",
        title: "2. Dados da Equipe de Estudantes e Coordenação",
        type: "numbered_section",
        content:
          "• Nome da Equipe / Projeto: {{nome_equipe}}\n• Integrantes (Estudantes): {{integrantes_com_matricula}}\n• Professor(a) Responsável / Orientador: {{professor_responsavel}} (Titulação: {{formacao_professor}} — Cargo: {{cargo_professor}})\n• Período Letivo / Semestre: {{periodo_letivo}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_necessidade",
        title: "3. Necessidade / Oportunidade Identificada",
        type: "numbered_section",
        content: "{{necessidade_identificada}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao",
        title: "4. Declaração de Aceite e Compromisso Mútuo",
        type: "declarations_list",
        content:
          "I. A organização parceira declara ter pleno conhecimento da natureza acadêmico-extensionista das atividades e autoriza a equipe de estudantes a realizar o levantamento de processos e requisitos técnicos necessários ao projeto.\n\nII. A equipe de estudantes e o IFPR comprometem-se a zelar pelo sigilo e confidencialidade de quaisquer dados sensíveis fornecidos pela parceira durante a execução das etapas extensionistas.\n\nIII. O parceiro compromete-se a disponibilizar canal de diálogo com a equipe para alinhamento de entregas e validação dos protótipos construídos.\n\nIV. A transferência do código-fonte e documentação resultante dar-se-á de forma livre e aberta, sem ônus financeiro para nenhuma das partes, visando o fortalecimento socioeconômico da comunidade local.",
        fontSize: 9.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_org",
        name: "nome_organizacao",
        label: "Nome da Organização / Entidade Parceira",
        type: "text",
        defaultValue: "Associação Comunitária de Moradores e Produtores de Ivaiporã",
        placeholder: "Ex: Associação Comercial, Cooperativa, Escola Municipal, APAE...",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_resp",
        name: "responsavel",
        label: "Responsável / Representante Legal",
        type: "text",
        defaultValue: "Carlos Eduardo Silva",
        placeholder: "Nome completo do representante legal",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_cargo_resp",
        name: "cargo_responsavel",
        label: "Cargo / Função do Representante",
        type: "text",
        defaultValue: "Presidente da Diretoria Executiva",
        placeholder: "Ex: Diretor Geral, Presidente, Coordenador...",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_contato",
        name: "contato",
        label: "Contato Telefônico e E-mail",
        type: "text",
        defaultValue: "(43) 99876-5432 / contato@associacao.org.br",
        placeholder: "Telefone / WhatsApp e e-mail institucional",
        required: true,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_end_parceiro",
        name: "endereco_parceiro",
        label: "Endereço da Entidade Parceira",
        type: "text",
        defaultValue: "Av. Brasil, nº 1250 - Centro, Ivaiporã - PR",
        placeholder: "Logradouro, número, bairro e cidade",
        required: false,
        section: "1. Dados do Parceiro",
      },
      {
        id: "fld_equipe",
        name: "nome_equipe",
        label: "Nome da Equipe / Projeto",
        type: "text",
        defaultValue: "",
        placeholder: "Preenchido automaticamente via Dados do Projeto",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_integrantes",
        name: "integrantes_com_matricula",
        label: "Integrantes da Equipe (Estudantes e Matrículas)",
        type: "textarea",
        defaultValue: "",
        placeholder: "Preenchido automaticamente via Dados do Projeto",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_prof",
        name: "professor_responsavel",
        label: "Professor(a) Responsável / Orientador",
        type: "text",
        defaultValue: "",
        placeholder: "Preenchido automaticamente via Dados do Projeto",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_periodo",
        name: "periodo_letivo",
        label: "Período Letivo / Semestre",
        type: "text",
        defaultValue: "",
        placeholder: "Ex: 2º Semestre / 2026",
        required: true,
        section: "2. Dados da Equipe",
      },
      {
        id: "fld_necessidade",
        name: "necessidade_identificada",
        label: "Necessidade / Oportunidade Identificada",
        type: "textarea",
        defaultValue:
          "Identificou-se a necessidade de um mecanismo digital centralizado para registro, catalogação e recuperação transparente de demandas e bens da entidade, eliminando o controle físico manual e reduzindo tempo de atendimento aos cidadãos através de um sistema web e mobile intuitivo.",
        placeholder: "Descreva a oportunidade diagnosticada e o benefício comunitário gerado",
        required: true,
        section: "3. Necessidade Identificada",
      },
      {
        id: "fld_data",
        name: "data",
        label: "Data do Documento",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "Local e Assinaturas",
      },
      {
        id: "fld_rep_equipe",
        name: "representante_equipe",
        label: "Representante da Equipe (Estudante Líder)",
        type: "text",
        defaultValue: "",
        placeholder: "Preenchido automaticamente via Dados do Projeto",
        required: true,
        section: "Local e Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_parceiro",
        title: "Representante da Organização Parceira",
        nameTag: "{{responsavel}}",
        roleTag: "{{cargo_responsavel}}",
        cpfOrDocTag: "{{nome_organizacao}}",
      },
      {
        id: "sig_equipe",
        title: "Representante da Equipe de Estudantes",
        nameTag: "{{representante_equipe}}",
        roleTag: "Líder da Equipe - BSI IFPR",
        cpfOrDocTag: "Campus Ivaiporã",
      },
      {
        id: "sig_orientador",
        title: "Visto do Professor(a) Orientador(a)",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 2. Termo de Responsabilidade
  {
    id: "tpl_termo_responsabilidade",
    title: "Termo de Responsabilidade e Compromisso",
    code: "PAT-RESP-02",
    category: "RESPONSABILIDADE",
    description: "Termo de responsabilidade formal pela guarda, integridade, custódia e correto uso de equipamentos e recursos do projeto.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nSETOR DE PATRIMÔNIO, TI E PROJETOS DE EXTENSÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_intro_resp",
        title: "Objeto e Finalidade",
        type: "paragraph",
        content:
          "Pelo presente Termo de Responsabilidade e Compromisso, o(a) signatário(a) abaixo qualificado(a) assume a guarda, zelo e custódia temporária dos bens e recursos institucionais descritos neste instrumento, vinculados ao desenvolvimento das atividades do Projeto de Extensão {{nome_equipe}} do curso de {{curso}} do {{instituicao}} - {{campus}}.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_dados_resp",
        title: "1. Qualificação do(a) Responsável / Depositário(a)",
        type: "numbered_section",
        content:
          "• Nome Completo: {{nome_responsavel}}\n• Matrícula / CPF: {{documento_responsavel}}\n• Vínculo Institucional / Função: {{vinculo_responsavel}}\n• Curso / Setor de Lotação: {{curso_setor}}\n• Contato (Telefone e E-mail): {{contato_responsavel}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_itens_resp",
        title: "2. Discriminação dos Bens e Equipamentos",
        type: "numbered_section",
        content:
          "• Descrição dos Equipamentos / Bens: {{descricao_equipamentos}}\n• Número(s) de Patrimônio / Tombamento / Série: {{patrimonio_equipamentos}}\n• Estado de Conservação na Entrega: {{estado_conservacao}}\n• Finalidade Específica de Uso: {{finalidade_uso}}\n• Prazo Previsto para Devolução: {{prazo_devolucao}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_clausulas_resp",
        title: "3. Cláusulas e Compromissos Firmados",
        type: "declarations_list",
        content:
          "I. O(A) responsável compromete-se a utilizar os bens única e exclusivamente para as finalidades institucionais, acadêmicas e extensionistas do projeto, zelando por sua integridade física e lógica.\n\nII. É vedado ceder, transferir, emprestar ou sublocar os bens a terceiros não autorizados formalmente pela coordenação do projeto.\n\nIII. Em caso de extravio, dano ou sinistro decorrente de mau uso ou negligência, o(a) responsável comunicará imediatamente à coordenação para as devidas providências institucionais.\n\nIV. A devolução dos bens dar-se-á mediante conferência técnica na data estipulada ou a qualquer momento mediante requisição do IFPR.",
        fontSize: 9.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_resp",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_resp_nome",
        name: "nome_responsavel",
        label: "Nome Completo do Responsável",
        type: "text",
        defaultValue: "Paulo Cauan Lima Pereira",
        placeholder: "Nome do responsável ou depositário",
        required: true,
        section: "1. Qualificação do Responsável",
      },
      {
        id: "fld_resp_doc",
        name: "documento_responsavel",
        label: "Matrícula ou CPF",
        type: "text",
        defaultValue: "20251IVA10030008",
        placeholder: "Matrícula estudantil ou CPF",
        required: true,
        section: "1. Qualificação do Responsável",
      },
      {
        id: "fld_resp_vinc",
        name: "vinculo_responsavel",
        label: "Vínculo Institucional",
        type: "text",
        defaultValue: "Estudante Pesquisador / Desenvolvedor",
        placeholder: "Ex: Estudante BSI, Servidor Docente, Bolsista...",
        required: true,
        section: "1. Qualificação do Responsável",
      },
      {
        id: "fld_resp_curso",
        name: "curso_setor",
        label: "Curso ou Setor de Lotação",
        type: "text",
        defaultValue: "Bacharelado em Sistemas de Informação",
        placeholder: "Ex: BSI Campus Ivaiporã",
        required: true,
        section: "1. Qualificação do Responsável",
      },
      {
        id: "fld_resp_contato",
        name: "contato_responsavel",
        label: "Contato (Telefone e E-mail)",
        type: "text",
        defaultValue: "(43) 99999-0000 / paulocauan39@gmail.com",
        placeholder: "Telefone / e-mail",
        required: true,
        section: "1. Qualificação do Responsável",
      },
      {
        id: "fld_resp_desc",
        name: "descricao_equipamentos",
        label: "Descrição dos Bens / Equipamentos",
        type: "textarea",
        defaultValue: "01 Notebook Dell Latitude Core i5, 16GB RAM, SSD 512GB com carregador original e mouse óptico.",
        placeholder: "Descrição detalhada dos equipamentos e acessórios cedidos",
        required: true,
        section: "2. Bens e Equipamentos",
      },
      {
        id: "fld_resp_patrimonio",
        name: "patrimonio_equipamentos",
        label: "Nº de Patrimônio / Tombamento / Série",
        type: "text",
        defaultValue: "IFPR-PAT-049281 / S/N: BR-9402X",
        placeholder: "Plaquetas de patrimônio ou números de série",
        required: true,
        section: "2. Bens e Equipamentos",
      },
      {
        id: "fld_resp_estado",
        name: "estado_conservacao",
        label: "Estado de Conservação na Entrega",
        type: "text",
        defaultValue: "Excelente estado de funcionamento e conservação física",
        placeholder: "Ex: Novo, Em bom estado, Sem avarias...",
        required: true,
        section: "2. Bens e Equipamentos",
      },
      {
        id: "fld_resp_finalidade",
        name: "finalidade_uso",
        label: "Finalidade Específica do Uso",
        type: "text",
        defaultValue: "Desenvolvimento, testes e suporte da plataforma Localiza+ / InovaIF",
        placeholder: "Finalidade acadêmica ou extensionista",
        required: true,
        section: "2. Bens e Equipamentos",
      },
      {
        id: "fld_resp_prazo",
        name: "prazo_devolucao",
        label: "Prazo Previsto de Devolução",
        type: "text",
        defaultValue: "Término do ano letivo / Dezembro de 2026",
        placeholder: "Data ou evento de devolução",
        required: true,
        section: "2. Bens e Equipamentos",
      },
      {
        id: "fld_resp_data",
        name: "data",
        label: "Data do Termo",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_resp_titular",
        title: "Responsável pelo Bem / Depositário(a)",
        nameTag: "{{nome_responsavel}}",
        roleTag: "{{vinculo_responsavel}}",
        cpfOrDocTag: "{{documento_responsavel}}",
      },
      {
        id: "sig_resp_coord",
        title: "Coordenação / Professor Orientador",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 3. Declaração de Participação (Geral)
  {
    id: "tpl_declaracao_participacao_geral",
    title: "Declaração de Participação",
    code: "DECL-PART-03",
    category: "DECLARACOES",
    description: "Declaração de participação em atividades acadêmicas, oficinas, eventos ou desenvolvimento no âmbito do IFPR Campus Ivaiporã.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nDIRETORIA DE ENSINO, PESQUISA E EXTENSÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_decl_geral_tit",
        title: "DECLARAÇÃO",
        type: "paragraph",
        content: "D E C L A R A Ç Ã O",
        fontSize: 14,
        isBold: true,
        isItalic: false,
        align: "center",
        spacingBottom: 6,
      },
      {
        id: "sec_decl_geral_corpo",
        title: "Texto da Declaração",
        type: "paragraph",
        content:
          "Declaramos, para os devidos fins de comprovação e registro institucional, que {{nome_participante}}, documento {{documento_participante}}, participou das atividades de \"{{atividade_participada}}\", vinculado(a) à equipe {{nome_equipe}} do curso de {{curso}} do {{instituicao}} - {{campus}}.",
        fontSize: 11,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_decl_geral_detalhes",
        title: "1. Detalhamento e Carga Horária",
        type: "numbered_section",
        content:
          "• Atividade / Função: {{funcao_participante}}\n• Período de Realização: de {{data_inicio_participacao}} a {{data_termino_participacao}}\n• Carga Horária Total: {{carga_horaria_total}} horas\n• Descrição das Ações: {{resumo_atividades_desenvolvidas}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_decl_geral_finalidade",
        title: "2. Finalidade",
        type: "paragraph",
        content:
          "Por ser a expressão da verdade e para que surta seus efeitos legais e pedagógicos, firmamos a presente declaração.",
        fontSize: 10,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_decl_geral_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_dgen_nome",
        name: "nome_participante",
        label: "Nome Completo do(a) Participante",
        type: "text",
        defaultValue: "Gabriel Oliveira da Silva",
        placeholder: "Nome do participante",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_dgen_doc",
        name: "documento_participante",
        label: "Documento de Identificação (CPF/RG/Matrícula)",
        type: "text",
        defaultValue: "CPF: 123.456.789-00 / Matrícula: 20251IVA10030010",
        placeholder: "Documento oficial ou matrícula",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_dgen_ativ",
        name: "atividade_participada",
        label: "Nome da Atividade / Evento / Projeto",
        type: "text",
        defaultValue: "Oficinas de Tecnologia e Implantação do Sistema Localiza+",
        placeholder: "Ex: Capacitação, Workshop, Desenvolvimento de Software...",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_func",
        name: "funcao_participante",
        label: "Função / Atuação Desempenhada",
        type: "text",
        defaultValue: "Ministrante / Desenvolvedor",
        placeholder: "Ex: Ouvinte, Participante, Monitor, Palestrante...",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_ini",
        name: "data_inicio_participacao",
        label: "Data de Início",
        type: "text",
        defaultValue: "01 de abril de 2026",
        placeholder: "Data de início",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_fim",
        name: "data_termino_participacao",
        label: "Data de Término",
        type: "text",
        defaultValue: "30 de junho de 2026",
        placeholder: "Data de término",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_ch",
        name: "carga_horaria_total",
        label: "Carga Horária Total (Horas)",
        type: "text",
        defaultValue: "40 (quarenta)",
        placeholder: "Ex: 20, 40, 80...",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_desc",
        name: "resumo_atividades_desenvolvidas",
        label: "Resumo das Ações Realizadas",
        type: "textarea",
        defaultValue: "Participação ativa nas atividades de planejamento, execução prática, oficinas com a comunidade e elaboração de relatórios técnicos.",
        placeholder: "Breve descrição das ações",
        required: true,
        section: "2. Atividades e Período",
      },
      {
        id: "fld_dgen_data",
        name: "data",
        label: "Data da Emissão",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_dgen_coord",
        title: "Coordenação / Responsável",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
      {
        id: "sig_dgen_dir",
        title: "Diretoria de Ensino, Pesquisa e Extensão",
        nameTag: "Coordenação Geral de Ensino",
        roleTag: "IFPR Campus Ivaiporã",
        cpfOrDocTag: "Portaria Institucional",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 4. Relatório de Atividades
  {
    id: "tpl_relatorio_atividades",
    title: "Relatório de Atividades",
    code: "EXT-REL-04",
    category: "EXTENSAO",
    description: "Relatório técnico periódico de execução, métricas comunitárias, resultados obtidos e planejamento de atividades extensionistas.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nRELATÓRIO TÉCNICO-EXECUTIVO DE ATIVIDADES EXTENSIONISTAS",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_rel_intro",
        title: "1. Identificação do Projeto e Equipe",
        type: "numbered_section",
        content:
          "• Título do Relatório: {{titulo_relatorio}}\n• Equipe de Estudantes: {{nome_equipe}} ({{integrantes}})\n• Período de Referência: {{periodo_relatorio}}\n• Professor(a) Orientador(a): {{professor_responsavel}} ({{cargo_professor}})\n• Comunidade / Parceiros Atendidos: {{parceiros_atendidos}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_rel_resumo",
        title: "2. Resumo Executivo das Atividades Realizadas",
        type: "paragraph",
        content: "{{resumo_executivo_acoes}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_rel_metricas",
        title: "3. Resultados Alcançados e Métricas",
        type: "numbered_section",
        content:
          "• Total de Atendimentos / Cadastros Realizados: {{total_atendimentos}}\n• Taxa de Resolução / Efetividade: {{indice_resolucao}}\n• Entregas de Software / Módulos Concluídos: {{entregas_concluidas}}\n• Treinamentos e Oficinas Ministradas: {{treinamentos_realizados}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_rel_proximos",
        title: "4. Dificuldades Encontradas e Próximos Passos",
        type: "paragraph",
        content: "{{proximos_passos_planejamento}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_rel_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_rel_tit",
        name: "titulo_relatorio",
        label: "Título do Relatório",
        type: "text",
        defaultValue: "Relatório de Atividades Extensionistas - Projeto Localiza+ / InovaIF",
        placeholder: "Título do relatório",
        required: true,
        section: "1. Identificação",
      },
      {
        id: "fld_rel_per",
        name: "periodo_relatorio",
        label: "Período de Referência",
        type: "text",
        defaultValue: "1º Semestre de 2026 (Março a Julho)",
        placeholder: "Ex: 2º Semestre de 2026",
        required: true,
        section: "1. Identificação",
      },
      {
        id: "fld_rel_parceiros",
        name: "parceiros_atendidos",
        label: "Parceiros / Comunidade Atendida",
        type: "text",
        defaultValue: "Comunidade Acadêmica do IFPR Campus Ivaiporã e Cidadãos Locais",
        placeholder: "Entidades e grupos atendidos",
        required: true,
        section: "1. Identificação",
      },
      {
        id: "fld_rel_resumo",
        name: "resumo_executivo_acoes",
        label: "Resumo das Ações Realizadas",
        type: "textarea",
        defaultValue: "A equipe realizou o levantamento de requisitos, arquitetura de software, desenvolvimento da plataforma web/mobile, implantação dos painéis administrativos e workshops práticos de atendimento à comunidade.",
        placeholder: "Descrição das atividades executadas",
        required: true,
        section: "2. Resumo Executivo",
      },
      {
        id: "fld_rel_atend",
        name: "total_atendimentos",
        label: "Total de Atendimentos / Cadastros",
        type: "text",
        defaultValue: "148 ocorrências processadas no sistema",
        placeholder: "Ex: 85 itens registrados, 42 devolvidos",
        required: true,
        section: "3. Resultados e Métricas",
      },
      {
        id: "fld_rel_resol",
        name: "indice_resolucao",
        label: "Índice de Resolução / Efetividade",
        type: "text",
        defaultValue: "87.5% de taxa de restituição de pertences aos legítimos donos",
        placeholder: "Taxa de resolução",
        required: true,
        section: "3. Resultados e Métricas",
      },
      {
        id: "fld_rel_entregas",
        name: "entregas_concluidas",
        label: "Entregas Computacionais Concluídas",
        type: "textarea",
        defaultValue: "Módulo de Gerenciamento de Documentos PDF, QR Code para rastreabilidade de itens, Módulo AI Match e Painel de Transparência.",
        placeholder: "Entregas do sistema",
        required: true,
        section: "3. Resultados e Métricas",
      },
      {
        id: "fld_rel_trein",
        name: "treinamentos_realizados",
        label: "Treinamentos e Oficinas Realizadas",
        type: "text",
        defaultValue: "03 capacitações práticas com servidores e monitores",
        placeholder: "Oficinas realizadas",
        required: true,
        section: "3. Resultados e Métricas",
      },
      {
        id: "fld_rel_prox",
        name: "proximos_passos_planejamento",
        label: "Observações e Próximos Passos",
        type: "textarea",
        defaultValue: "Expansão dos pontos de coleta com parceiros comunitários e publicação dos resultados em eventos científicos da Rede Federal.",
        placeholder: "Próximos passos e melhorias",
        required: true,
        section: "4. Próximos Passos",
      },
      {
        id: "fld_rel_data",
        name: "data",
        label: "Data do Relatório",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "5. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_rel_lider",
        title: "Representante da Equipe",
        nameTag: "{{representante_equipe}}",
        roleTag: "Líder da Equipe — InovaIF",
        cpfOrDocTag: "IFPR Campus Ivaiporã",
      },
      {
        id: "sig_rel_orientador",
        title: "Professor(a) Orientador(a) / Coordenador(a)",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 5. Declaração de Participação em Projeto de Extensão
  {
    id: "tpl_declaracao_participacao_extensao",
    title: "Declaração de Participação em Projeto de Extensão",
    code: "EXT-DECL-05",
    category: "DECLARACOES",
    description: "Declaração oficial comprobatória de participação em projeto extensionista para fins de curricularização da extensão e atividades complementares.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nDIRETORIA DE ENSINO, PESQUISA E EXTENSÃO · COORDENAÇÃO DE EXTENSÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_decl_titulo",
        title: "DECLARAÇÃO",
        type: "paragraph",
        content: "D E C L A R A Ç Ã O   D E   E X T E N S Ã O",
        fontSize: 14,
        isBold: true,
        isItalic: false,
        align: "center",
        spacingBottom: 6,
      },
      {
        id: "sec_decl_corpo",
        title: "Texto da Declaração",
        type: "paragraph",
        content:
          "Declaramos, para os devidos fins de comprovação acadêmica e curricular, que {{nome_participante}}, portador(a) do documento {{documento_participante}} e matrícula {{matricula_participante}}, participou ativamente como {{funcao_participante}} no Projeto de Extensão Universitária intitulado \"{{nome_projeto_extensao}}\", desenvolvido no âmbito do curso de {{curso}} do {{instituicao}} - {{campus}}.",
        fontSize: 11,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_decl_detalhes",
        title: "1. Período e Carga Horária Cumprida",
        type: "numbered_section",
        content:
          "• Período de Realização: de {{data_inicio_participacao}} a {{data_termino_participacao}}\n• Carga Horária Total Cumprida: {{carga_horaria_total}} horas de atividades extensionistas\n• Natureza das Atividades: {{resumo_atividades_desenvolvidas}}\n• Orientação Docente: {{professor_responsavel}} ({{cargo_professor}})",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_decl_validacao",
        title: "2. Autenticidade Institucional",
        type: "paragraph",
        content:
          "Esta declaração possui fé pública institucional para fins de integralização de Atividades Complementares (AC), Curricularização da Extensão e enriquecimento curricular de acordo com as normas pedagógicas vigentes do IFPR.",
        fontSize: 9.5,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_decl_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_decl_nome",
        name: "nome_participante",
        label: "Nome Completo do(a) Participante",
        type: "text",
        defaultValue: "Gabriel Oliveira da Silva",
        placeholder: "Nome do estudante ou colaborador",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_decl_doc",
        name: "documento_participante",
        label: "Documento de Identificação (RG/CPF)",
        type: "text",
        defaultValue: "RG 13.987.654-2 SSP/PR",
        placeholder: "RG ou CPF",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_decl_mat",
        name: "matricula_participante",
        label: "Número de Matrícula",
        type: "text",
        defaultValue: "20251IVA10030010",
        placeholder: "Matrícula institucional",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_decl_func",
        name: "funcao_participante",
        label: "Função / Atuação no Projeto",
        type: "text",
        defaultValue: "Estudante Desenvolvedor e Pesquisador Extensionista",
        placeholder: "Ex: Bolsista de Extensão, Voluntário, Desenvolvedor...",
        required: true,
        section: "1. Participante",
      },
      {
        id: "fld_decl_proj",
        name: "nome_projeto_extensao",
        label: "Nome do Projeto de Extensão",
        type: "text",
        defaultValue: "Localiza+ : Sistema Institucional de Achados, Perdidos e Atendimento Comunitário",
        placeholder: "Nome do projeto de extensão",
        required: true,
        section: "2. Projeto e Atividades",
      },
      {
        id: "fld_decl_ini",
        name: "data_inicio_participacao",
        label: "Data de Início",
        type: "text",
        defaultValue: "01 de março de 2026",
        placeholder: "Data de início",
        required: true,
        section: "2. Projeto e Atividades",
      },
      {
        id: "fld_decl_fim",
        name: "data_termino_participacao",
        label: "Data de Término / Conclusão",
        type: "text",
        defaultValue: "15 de dezembro de 2026",
        placeholder: "Data de encerramento",
        required: true,
        section: "2. Projeto e Atividades",
      },
      {
        id: "fld_decl_ch",
        name: "carga_horaria_total",
        label: "Carga Horária Total (Horas)",
        type: "text",
        defaultValue: "120 (cento e vinte)",
        placeholder: "Ex: 60, 120, 180...",
        required: true,
        section: "2. Projeto e Atividades",
      },
      {
        id: "fld_decl_ativ",
        name: "resumo_atividades_desenvolvidas",
        label: "Resumo das Atividades Desenvolvidas",
        type: "textarea",
        defaultValue: "Diagnóstico de processos comunitários, modelagem e desenvolvimento do sistema computacional web/mobile, realização de testes com a comunidade e documentação técnica.",
        placeholder: "Descrição detalhada das atividades",
        required: true,
        section: "2. Projeto e Atividades",
      },
      {
        id: "fld_decl_data",
        name: "data",
        label: "Data de Emissão",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_decl_prof",
        title: "Professor(a) Orientador(a) / Coordenador(a)",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
      {
        id: "sig_decl_dir",
        title: "Coordenação de Extensão / Direção de Ensino",
        nameTag: "Coordenação de Extensão e Relações Comunitárias",
        roleTag: "IFPR Campus Ivaiporã",
        cpfOrDocTag: "Portaria de Homologação",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 6. Termo de Autorização de Uso de Imagem
  {
    id: "tpl_autorizacao_uso_imagem",
    title: "Termo de Autorização de Uso de Imagem e Voz",
    code: "AUT-IMG-06",
    category: "RESPONSABILIDADE",
    description: "Termo formal de cessão e autorização para uso de imagem e depoimentos em materiais de divulgação acadêmica, relatórios e eventos do projeto.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nCOMUNICAÇÃO INSTITUCIONAL E PROJETOS DE EXTENSÃO",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_img_intro",
        title: "Declaração e Finalidade",
        type: "paragraph",
        content:
          "Pelo presente instrumento particular, o(a) AUTORIZANTE abaixo qualificado(a) autoriza de forma livre, espontânea e a título gratuito o {{instituicao}} - {{campus}} e a equipe do projeto {{nome_equipe}} a captar, fixar, reproduzir e veicular sua imagem, som de voz e depoimentos.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_img_qualificacao",
        title: "1. Qualificação do(a) Autorizante",
        type: "numbered_section",
        content:
          "• Nome Completo: {{nome_autorizante}}\n• CPF / RG: {{cpf_autorizante}} / {{rg_autorizante}}\n• Nacionalidade / Estado Civil: {{nacionalidade_autorizante}} / {{estado_civil_autorizante}}\n• Vínculo / Profissão: {{vinculo_autorizante}}\n• Endereço: {{endereco_autorizante}}\n• Telefone e E-mail: {{contato_autorizante}}\n• Responsável Legal (se menor de idade): {{responsavel_legal_menor}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_img_finalidades",
        title: "2. Finalidades e Condições da Autorização",
        type: "declarations_list",
        content:
          "I. A presente autorização destina-se exclusivamente a fins pedagógicos, acadêmicos, científicos, culturais e institucionais de divulgação das ações do Projeto de Extensão {{nome_equipe}} do curso de {{curso}} do IFPR Campus Ivaiporã.\n\nII. As imagens e gravações poderão ser veiculadas em sítios eletrônicos oficiais, redes sociais institucionais, apresentações em congressos, feiras de ciências, artigos científicos e materiais impressos do IFPR.\n\nIII. A autorização é concedida a título gratuito, não cabendo qualquer espécie de remuneração, compensação financeira ou indenização presente ou futura.\n\nIV. O IFPR compromete-se a não utilizar a imagem de forma descontextualizada ou que atente contra a moral, honra ou intimidade do autorizante.",
        fontSize: 9.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_img_data",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_img_nome",
        name: "nome_autorizante",
        label: "Nome Completo do(a) Autorizante",
        type: "text",
        defaultValue: "Mariana Alcantara Lopes",
        placeholder: "Nome completo de quem autoriza o uso da imagem",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_cpf",
        name: "cpf_autorizante",
        label: "CPF",
        type: "text",
        defaultValue: "123.456.789-00",
        placeholder: "000.000.000-00",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_rg",
        name: "rg_autorizante",
        label: "RG / Órgão Emissor",
        type: "text",
        defaultValue: "12.345.678-9 SSP/PR",
        placeholder: "RG com órgão expedidor",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_nac",
        name: "nacionalidade_autorizante",
        label: "Nacionalidade",
        type: "text",
        defaultValue: "Brasileira",
        placeholder: "Ex: Brasileira",
        required: false,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_civ",
        name: "estado_civil_autorizante",
        label: "Estado Civil",
        type: "text",
        defaultValue: "Solteira",
        placeholder: "Ex: Solteiro(a), Casado(a)...",
        required: false,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_vinc",
        name: "vinculo_autorizante",
        label: "Vínculo / Profissão",
        type: "text",
        defaultValue: "Estudante / Membro da Comunidade Local",
        placeholder: "Ex: Estudante, Produtor Rural, Servidor...",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_end",
        name: "endereco_autorizante",
        label: "Endereço Residencial",
        type: "text",
        defaultValue: "Rua Curitiba, nº 320 - Centro, Ivaiporã - PR",
        placeholder: "Endereço completo",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_cont",
        name: "contato_autorizante",
        label: "Telefone / E-mail",
        type: "text",
        defaultValue: "(43) 99888-7766 / mariana@email.com",
        placeholder: "Telefone e e-mail",
        required: true,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_resp",
        name: "responsavel_legal_menor",
        label: "Responsável Legal (Se menor de 18 anos)",
        type: "text",
        defaultValue: "Não se aplica (Maior de idade)",
        placeholder: "Nome e CPF do responsável legal se menor, ou 'Não se aplica'",
        required: false,
        section: "1. Qualificação",
      },
      {
        id: "fld_img_data",
        name: "data",
        label: "Data do Termo",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "2. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_img_autorizante",
        title: "Assinatura do(a) Autorizante",
        nameTag: "{{nome_autorizante}}",
        roleTag: "Autorizante",
        cpfOrDocTag: "CPF: {{cpf_autorizante}}",
      },
      {
        id: "sig_img_coord",
        title: "Coordenação / Representante do Projeto",
        nameTag: "{{professor_responsavel}}",
        roleTag: "{{cargo_professor}}",
        cpfOrDocTag: "{{instituicao}} — {{campus}}",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 7. Termo de Entrega e Devolução de Objeto de Valor (Institucional / Achados & Perdidos)
  {
    id: "tpl_termo_devolucao_objeto",
    title: "Termo de Entrega e Devolução de Objeto de Valor",
    code: "SEC-DEV-07",
    category: "ACHADOS_PERDIDOS",
    description: "Comprovante formal com fé pública de devolução de pertences custodiados pelo balcão de Achados e Perdidos do IFPR Campus Ivaiporã.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nSETOR DE ATENDIMENTO E CUSTÓDIA DE PERTENCES · SEBAC",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_intro_dev",
        title: "Declaração de Retirada e Entrega",
        type: "paragraph",
        content:
          "O presente Termo atesta que o objeto abaixo descrito, custodiado no setor de Achados e Perdidos do IFPR Campus Ivaiporã, foi devidamente devolvido ao seu legítimo proprietário/reclamante após conferência documental e comprovação de titularidade.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_item_dev",
        title: "1. Identificação do Objeto Custodiado",
        type: "numbered_section",
        content:
          "• Descrição do Item: {{titulo_item}}\n• Categoria / Cor / Marca: {{categoria_item}} / {{cor_item}} / {{marca_item}}\n• Código de Rastreabilidade / Protocolo: {{codigo_protocolo}}\n• Local e Data do Recolhimento: {{local_recolhimento}} em {{data_recolhimento}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_retirante_dev",
        title: "2. Dados do Reclamante / Proprietário",
        type: "numbered_section",
        content:
          "• Nome Completo: {{nome_reclamante}}\n• Vínculo Institucional / Curso: {{vinculo_reclamante}}\n• Matrícula / CPF / RG: {{documento_reclamante}}\n• Contato Telefônico / E-mail: {{contato_reclamante}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao_dev",
        title: "3. Declaração do Reclamante",
        type: "declarations_list",
        content:
          "Declaro, sob as penas da lei e do regulamento disciplinar do IFPR, que recebi o bem acima caracterizado em perfeito estado de conservação, dando plena e irrevogável quitação de custódia à instituição.",
        fontSize: 10,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_dev",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_tit_item",
        name: "titulo_item",
        label: "Título / Descrição do Item",
        type: "text",
        defaultValue: "Notebook Dell Inspiron 15 Cinza + Carregador",
        placeholder: "Ex: Smartphone Samsung Galaxy, Chaves...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_cat_item",
        name: "categoria_item",
        label: "Categoria do Item",
        type: "text",
        defaultValue: "Eletrônicos & Informática",
        placeholder: "Ex: Documentos, Eletrônicos...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_cor_item",
        name: "cor_item",
        label: "Cor Predominante",
        type: "text",
        defaultValue: "Cinza Metálico",
        placeholder: "Ex: Preto, Azul...",
        required: false,
        section: "1. Dados do Item",
      },
      {
        id: "fld_marca_item",
        name: "marca_item",
        label: "Marca / Modelo",
        type: "text",
        defaultValue: "Dell Inspiron 15",
        placeholder: "Ex: Apple, Samsung, Nike...",
        required: false,
        section: "1. Dados do Item",
      },
      {
        id: "fld_prot_item",
        name: "codigo_protocolo",
        label: "Código / Protocolo do Sistema",
        type: "text",
        defaultValue: "IFPR-2026-B8492X",
        placeholder: "Protocolo do registro",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_loc_item",
        name: "local_recolhimento",
        label: "Local do Recolhimento",
        type: "text",
        defaultValue: "Laboratório de Informática 03 (Bloco B)",
        placeholder: "Ex: Biblioteca, Pátio...",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_dt_item",
        name: "data_recolhimento",
        label: "Data do Recolhimento",
        type: "text",
        defaultValue: "10 de agosto de 2026",
        placeholder: "Data em que foi encontrado",
        required: true,
        section: "1. Dados do Item",
      },
      {
        id: "fld_rec_nome",
        name: "nome_reclamante",
        label: "Nome do Reclamante / Proprietário",
        type: "text",
        defaultValue: "Mariana Alcantara Lopes",
        placeholder: "Nome completo de quem está retirando",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_vinc",
        name: "vinculo_reclamante",
        label: "Vínculo Institucional",
        type: "text",
        defaultValue: "Estudante - Técnico em Informática Integrado",
        placeholder: "Ex: Estudante BSI, Servidor Docente, Visitante...",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_doc",
        name: "documento_reclamante",
        label: "Matrícula / Documento (CPF ou RG)",
        type: "text",
        defaultValue: "Matrícula: 2024104928 / RG: 12.345.678-9 PR",
        placeholder: "Matrícula ou CPF/RG",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_rec_cont",
        name: "contato_reclamante",
        label: "Telefone e E-mail de Contato",
        type: "text",
        defaultValue: "(43) 98877-6655 / mariana.lopes@estudantes.ifpr.edu.br",
        placeholder: "Telefone / E-mail",
        required: true,
        section: "2. Reclamante",
      },
      {
        id: "fld_serv_nome",
        name: "servidor_atendente",
        label: "Nome do Servidor Responsável pela Entrega",
        type: "text",
        defaultValue: "Paulo Cauan - Administrador TI",
        placeholder: "Nome do servidor responsável",
        required: true,
        section: "3. Atendimento",
      },
      {
        id: "fld_data_dev",
        name: "data",
        label: "Data da Devolução",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Atendimento",
      },
    ],
    signatures: [
      {
        id: "sig_rec",
        title: "Reclamante / Proprietário do Objeto",
        nameTag: "{{nome_reclamante}}",
        roleTag: "{{vinculo_reclamante}}",
        cpfOrDocTag: "{{documento_reclamante}}",
      },
      {
        id: "sig_serv",
        title: "Servidor / Atendente Responsável (IFPR)",
        nameTag: "{{servidor_atendente}}",
        roleTag: "Setor de Custódia e Patrimônio",
        cpfOrDocTag: "IFPR Campus Ivaiporã",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },

  // 8. Termo de Destinação e Doação Comunitária (Institucional)
  {
    id: "tpl_termo_doacao_objeto",
    title: "Termo de Destinação e Doação Comunitária",
    code: "DIR-DOA-08",
    category: "INSTITUCIONAL",
    description: "Termo legal de doação de bens não reclamados após o prazo regulamentar de guarda para instituições filantrópicas de Ivaiporã.",
    status: "ATIVO",
    version: 1,
    headerText: "REPÚBLICA FEDERATIVA DO BRASIL\nMINISTÉRIO DA EDUCAÇÃO\n{{instituicao}} — {{campus}}\nDIREÇÃO GERAL · COMISSÃO PERMANENTE DE DESTINAÇÃO DE BENS",
    institutionLogoUrl: "",
    includeLogo: true,
    includeDocNumber: true,
    includeHeader: true,
    includeFooter: true,
    footerText: "{{instituicao}} — {{campus}} · {{endereco_completo}}",
    sections: [
      {
        id: "sec_intro_doa",
        title: "Fundamentação e Finalidade",
        type: "paragraph",
        content:
          "O presente Termo de Doação formaliza a entrega e transferência de titularidade de bens e vestuários não reclamados, após escoado o prazo regulamentar de 90 (noventa) dias de guarda no setor de Achados e Perdidos do IFPR Campus Ivaiporã, nos termos do Regulamento Interno de Custódia e da legislação vigente de destinação social de bens.",
        fontSize: 10.5,
        isBold: false,
        isItalic: false,
        align: "justify",
        spacingBottom: 4,
      },
      {
        id: "sec_entidade_doa",
        title: "1. Entidade Filantrópica / Donatária Beneficiada",
        type: "numbered_section",
        content:
          "• Razão Social / Nome da Entidade: {{entidade_donataria}}\n• CNPJ: {{cnpj_donataria}}\n• Representante Legal: {{representante_donataria}}\n• Cargo / Função: {{cargo_donataria}}\n• Contato Telefônico: {{telefone_donataria}}\n• Endereço: {{endereco_donataria}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_itens_doa",
        title: "2. Relação de Itens Doados",
        type: "numbered_section",
        content:
          "• Quantidade Total de Itens: {{quantidade_itens}} volumes\n• Descrição Sintética dos Lotes: {{descricao_lotes}}\n• Prazo de Guarda Expirado em: {{data_expiracao_guarda}}",
        fontSize: 10,
        isBold: false,
        isItalic: false,
        align: "left",
        spacingBottom: 4,
      },
      {
        id: "sec_declaracao_doa",
        title: "3. Declaração de Recebimento",
        type: "declarations_list",
        content:
          "A entidade donatária declara ter recebido os bens relacionados para emprego exclusivo em suas finalidades estatutárias de assistência social, sem fins lucrativos, agradecendo a iniciativa comunitária do IFPR Campus Ivaiporã.",
        fontSize: 10,
        isBold: false,
        isItalic: true,
        align: "justify",
        spacingBottom: 6,
      },
      {
        id: "sec_local_doa",
        title: "Local e Data",
        type: "paragraph",
        content: "Ivaiporã - PR, {{data}}.",
        fontSize: 10.5,
        isBold: true,
        isItalic: false,
        align: "right",
        spacingBottom: 8,
      },
    ],
    fields: [
      {
        id: "fld_ent_doa",
        name: "entidade_donataria",
        label: "Nome da Entidade Donatária",
        type: "text",
        defaultValue: "Lar dos Idosos São Vicente de Paulo de Ivaiporã",
        placeholder: "Nome da instituição beneficente",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_cnpj_doa",
        name: "cnpj_donataria",
        label: "CNPJ da Entidade",
        type: "text",
        defaultValue: "75.123.456/0001-89",
        placeholder: "00.000.000/0000-00",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_rep_doa",
        name: "representante_donataria",
        label: "Representante Legal da Donatária",
        type: "text",
        defaultValue: "Ana Maria de Fátima Rezende",
        placeholder: "Nome do diretor/presidente",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_cargo_doa",
        name: "cargo_donataria",
        label: "Cargo / Função",
        type: "text",
        defaultValue: "Diretora Social",
        placeholder: "Ex: Presidente, Diretora...",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_tel_doa",
        name: "telefone_donataria",
        label: "Telefone de Contato",
        type: "text",
        defaultValue: "(43) 3472-1234",
        placeholder: "(00) 0000-0000",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_end_doa",
        name: "endereco_donataria",
        label: "Endereço da Entidade",
        type: "text",
        defaultValue: "Rua Ceará, nº 450 - Ivaiporã - PR",
        placeholder: "Endereço completo",
        required: true,
        section: "1. Entidade Donatária",
      },
      {
        id: "fld_qtd_doa",
        name: "quantidade_itens",
        label: "Quantidade Total de Itens",
        type: "text",
        defaultValue: "28 itens de vestuário e agasalhos",
        placeholder: "Ex: 15 peças de roupas, 5 garrafas...",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_desc_lotes",
        name: "descricao_lotes",
        label: "Descrição Sintética dos Lotes",
        type: "textarea",
        defaultValue: "Lote 01: 18 casacos e moletons infantis/adultos; Lote 02: 10 calças e agasalhos esportivos em perfeito estado de higienização.",
        placeholder: "Detalhamento dos lotes doados",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_dt_exp",
        name: "data_expiracao_guarda",
        label: "Data de Expiração do Prazo de Guarda",
        type: "text",
        defaultValue: "30 de junho de 2026",
        placeholder: "Data em que completou 90 dias",
        required: true,
        section: "2. Itens Doados",
      },
      {
        id: "fld_dir_ifpr",
        name: "diretor_ifpr",
        label: "Diretor Geral / Presidente da Comissão IFPR",
        type: "text",
        defaultValue: "Direção Geral do IFPR Campus Ivaiporã",
        placeholder: "Nome do Diretor Geral do Campus",
        required: true,
        section: "3. Assinaturas",
      },
      {
        id: "fld_data_doa",
        name: "data",
        label: "Data da Doação",
        type: "text",
        defaultValue: new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" }).format(new Date()),
        placeholder: "Data atual",
        required: true,
        section: "3. Assinaturas",
      },
    ],
    signatures: [
      {
        id: "sig_don",
        title: "Representante da Entidade Donatária",
        nameTag: "{{representante_donataria}}",
        roleTag: "{{cargo_donataria}}",
        cpfOrDocTag: "{{entidade_donataria}}",
      },
      {
        id: "sig_dir",
        title: "Direção Geral / Comissão Permanente",
        nameTag: "{{diretor_ifpr}}",
        roleTag: "Instituto Federal do Paraná",
        cpfOrDocTag: "Campus Ivaiporã",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdByName: "Administração IFPR TI",
    createdByEmail: "paulocauan39@gmail.com",
  },
];
